version: "2"  
services:  
    stratoblog:
        build: .
        ports:
            - "80:80"
        image: wesleycharlesblake/stratotechnology-blog
        restart: always
        volumes:
            - ./ghost_data/data:/ghost/content/data
            - ./ghost_data/images:/ghost/content/images
        environment:
            BLOG_URL: http://127.0.0.1
